- name: NGINX | Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true

- name: NGINX | Start nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
