- name: Joomla | Install unzip
  ansible.builtin.apt:
    name: unzip
    state: present
    update_cache: true

- name: Joomla | Download joomla
  ansible.builtin.get_url:
    url: "{{ joomla_url }}{{ joomla_major_version }}/{{ joomla_package_version }}/Joomla_{{ joomla_package_version }}-Stable-Full_Package.zip?format=zip"
    dest: /tmp/joomla.zip
    mode: '0644'

- name: Joomla | Unzip joomla
  ansible.builtin.unarchive:
    src: /tmp/joomla.zip
    dest: "{{ joomla_dir }}"
    remote_src: true

- name: Joomla | Set owner for Joomla files
  ansible.builtin.command:
    cmd: "chown -R www-data:www-data {{ joomla_dir }}"
  changed_when: false
  notify:
    - Restart nginx

- name: Joomla | Cleanup temporary files
  ansible.builtin.file:
    path: /tmp/joomla.zip
    state: absent
