- name: MYSQL | Install mysql
  ansible.builtin.apt:
    name: mysql-server
    state: present
    update_cache: true

- name: MYSQL | Start mysql
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true

- name: MYSQL | Install python3-pymysql
  ansible.builtin.apt:
    name: python3-pymysql
    state: present
    update_cache: true

- name: MYSQL | Set root password
  community.mysql.mysql_user:
    login_unix_socket: "/run/mysqld/mysqld.sock"
    name: "root"
    password: "{{ mysql_root_password }}"
    host_all: true
    state: present

- name: MYSQL | Create database
  community.mysql.mysql_db:
    name: "joomla"
    login_user: "root"
    login_password: "{{ mysql_root_password }}"
    state: present

- name: MYSQL | Create user
  community.mysql.mysql_user:
    name: "admin"
    password: "{{ mysql_admin_password }}"
    login_user: "root"
    login_password: "{{ mysql_root_password }}"
    priv: "*.*:ALL"
    state: present
